#!/usr/bin/ruby

def sql(query)
  ActiveRecord::Base.connection.select_all(query)
end

projectrc = File.expand_path('config/.projectrc')
if File.exist?(projectrc)
  load projectrc 
end

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end
