# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

source ~/.powerlevel10k/powerlevel10k.zsh-theme
source ~/.dotfiles/zsh/extra.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=./bin:$PATH

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
if [ -e /Users/kalv/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/kalv/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kalv/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/kalv/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kalv/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/kalv/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
