#!/usr/bin/env zsh

for found in ~/.dotfiles/dotfiles/*; do
  ln -fs $found ~/.$(basename $found)
done

chsh -s /bin/zsh

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

brew install zsh-history-substring-search
brew install zsh-syntax-highlighting
git clone git://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
